local newAnimations = {
	{
      Name = "StoryExpansion_Thanatos_Default",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Thanatos_01",
      InheritFrom = "Portrait_Base_01",
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Thanatos_Default_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Thanatos_01",
            OffsetX = -90,
      EndFrame = 1,
      StartFrame = 1,
    },
    {
      Name = "StoryExpansion_Thanatos_Pleased",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Thanatos_Pleased01",
      InheritFrom = "Portrait_Base_01",
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Thanatos_Pleased_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Thanatos_Pleased01",
            OffsetX = -90,
      EndFrame = 1,
      StartFrame = 1,
    },
    {
      Name = "StoryExpansion_Megaera_Default",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Megaera_01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Megaera_Default_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Megaera_01",
      OffsetY = 40,
      OffsetX = -90,
      EndFrame = 1,
      StartFrame = 1,
    },
    {
      Name = "StoryExpansion_Megaera_Pleased",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Megaera_Pleased01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 20,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Megaera_Pleased_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Megaera_Pleased01",
      OffsetY = 20,
      OffsetX = -90,
      EndFrame = 1,
      StartFrame = 1,
    },
    {
      Name = "StoryExpansion_Megaera_Standoffish",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Megaera_Standoffish01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 20,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Megaera_Standoffish_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Megaera_Standoffish01",
      OffsetY = 20,
      OffsetX = -90,
      EndFrame = 1,
      StartFrame = 1,
    },
    {
      Name = "StoryExpansion_Orpheus_Default",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Orpheus_01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Orpheus_Default_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Orpheus_01",
      OffsetY = 40,
      OffsetX = -90,
      EndFrame = 1,
      StartFrame = 1,
    },
    {
      Name = "StoryExpansion_Theseus",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Theseus_01",
      InheritFrom = "Portrait_Base_01",
      Scale = 0.9,
      OffsetY = -45
    },
    {
      Name = "StoryExpansion_Theseus_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Theseus_01",
      EndFrame = 1,
      StartFrame = 1,
      Scale = 0.9,
      OffsetY = -45
    },
    {
      Name = "StoryExpansion_Minotaur",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Minotaur_01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = -130.0
    },
    {
      Name = "StoryExpansion_Minotaur_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Minotaur_01",
      EndFrame = 1,
      StartFrame = 1,
      OffsetY = -130.0
    },
    {
      Name = "StoryExpansion_Hypnos_Default",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Hypnos_01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Hypnos_Default_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Hypnos_01",
      OffsetY = 40,
      OffsetX = -90,
      EndFrame = 1,
      StartFrame = 1,
    },
    {
      Name = "StoryExpansion_Patroclus_Default",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Patroclus_Neutral01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Patroclus_Default_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Patroclus_Neutral01",
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Dusa_Empathetic",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Medusa_Empathetic01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Dusa_Empathetic_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Medusa_Empathetic01",
      EndFrame = 1,
      StartFrame = 1,
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Dusa_Confident",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Medusa_Confident01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Dusa_Confident_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Medusa_Confident01",
      EndFrame = 1,
      StartFrame = 1,
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Dusa_Default",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Medusa_01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Dusa_Default_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Medusa_01",
      EndFrame = 1,
      StartFrame = 1,
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Eurydice_Default",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Eurydice_01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Eurydice_Default_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Eurydice_01",
      EndFrame = 1,
      StartFrame = 1,
      OffsetY = 40,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Hooded_Gaia",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Gaia_Hooded",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 10,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Hooded_Gaia_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Gaia_Hooded",
      EndFrame = 1,
      StartFrame = 1,
      OffsetY = 10,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Hooded_Chronos",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Chronos_Hooded_01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 10,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Hooded_Chronos_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Chronos_Hooded_01",
      EndFrame = 1,
      StartFrame = 1,
      OffsetY = 10,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Hooded_Ouranos",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Ouranos_Hooded_01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 10,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Hooded_Ouranos_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Ouranos_Hooded_01",
      EndFrame = 1,
      StartFrame = 1,
      OffsetY = 10,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Hooded_Rhea",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Rhea_Hooded_01",
      InheritFrom = "Portrait_Base_01",
      OffsetY = 10,
      OffsetX = -90,
    },
    {
      Name = "StoryExpansion_Hooded_Rhea_Exit",
      InheritFrom = "Portrait_Base_01_Exit",
      FilePath = "ReadEmAndWeep-Story_ExpansionGUI\\Portraits_Rhea_Hooded_01",
      EndFrame = 1,
      StartFrame = 1,
      OffsetY = 10,
      OffsetX = -90,
    },
    {
		Name = "Portrait_Poseidon_Default_InPerson_01",
		InheritFrom = "Portrait_Base_01",
		FilePath = "Portraits\\Poseidon\\Portraits_Poseidon_01",
		EndFrame = 1,
		StartFrame = 1,
		OffsetY = -260.0,
		OffsetX = 100,
		CreateAnimations = {
			{ Name = "Portrait_Poseidon_OlympianGlow_In" },
			{ Name = "Portrait_Poseidon_Wiggle1_In" },
			{ Name = "Portrait_Poseidon_Wiggle2_In" },
			{ Name = "Portrait_Poseidon_Wiggle3_In" },
			{ Name = "Portrait_Poseidon_Wiggle4_In" },
			{ Name = "Portrait_Poseidon_MainGlow"},
			{ Name = "Portrait_Poseidon_GlowLaurels"},
			{ Name = "Portrait_Poseidon_Glint" },
			{ Name = "Portrait_Poseidon_Blink" },
    },
	},
  {
		Name = "Portrait_Poseidon_Default_InPerson_01_Exit",
		InheritFrom = "Portrait_Base_01_Exit",
		FilePath = "Portraits\\Poseidon\\Portraits_Poseidon_01",
		EndFrame = 1,
		StartFrame = 1,
		OffsetY = -260.0,
		OffsetX = 100,
	}
}

local AnimationFile = rom.path.combine(rom.paths.Content(), 'Game\\Animations\\GUI_Portraits_VFX.sjson')


for k, newData in pairs(newAnimations) do
    sjson.hook(AnimationFile, function(data)
        table.insert(data.Animations, newData)
    end)
end