local newAnimations = {
    {
      Name = "StoryExpansionThanatosIdle",
      FilePath = "Animations\\NPCThanatos\\Idle\\ThanatosIdle",
      Type = "Book",
      VideoTexture = "ThanatosIdle_Bink",
      EndFrame = 60,
      Loop = true,
      NumAngles = 16,
      NumFrames = 60,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -100.0,
      Scale = 1.25,
      CancelOnOwnerMove = true,
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },
     {
      Name = "StoryExpansionThanatosIdleInhouse",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "ThanatosIdleInhouse_Bink",
      EndFrame = 60,
      Loop = true,
      NumAngles = 16,
      NumFrames = 60,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -66.0,
      Scale = 1.25,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },
{
      Name = "StoryExpansionThanatosIdleInhouseFidget_HairFlick",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse_Fidget_HairFlick\\ThanatosIdleInhouseFidget_HairFlick",
      Type = "Book",
      VideoTexture = "ThanatosIdleInhouseFidgetHairFlick__Bink",
      EndFrame = 90,
      Loop = false,
      NumAngles = 16,
      NumFrames = 90,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -66.0,
      Scale = 1.25,
      CancelOnOwnerMove = true,
      Sound = "/Leftovers/SFX/RobeFlutterInScene",
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },

--[[ 
    {
      Name = "ThanatosFire"
      FilePath = "Animations\NPCThanatos\Attack\ThanatosAttack"
      Type = "Book"
      VideoTexture = "ThanatosAttack_Bink"
      EndFrame = 70
      NumAngles = 8
      NumFrames = 70
      PlaySpeed = 30.0
      StartFrame = 1
      OffsetY = -100.0
      AllowRestart = true
      Slides = {
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 3 },
        { DurationFrames = 1 Sound = "/SFX/QuickSnap" Frame = 4 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 9 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 12 },
        { DurationFrames = 1 Sound = "/SFX/Player Sounds/ZagreusSwordLunge" Frame = 12 },
        { DurationFrames = 1 Sound = "/Leftovers/SFX/RobeFlutter" Frame = 21 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 52 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 56 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 63 },
      ]
      Material =
      {
        Ambient = 0.0
        Diffuse = 0.0
        Directionality = 0.0
      },
    },

    {
      Name = "ThanatosAoEFire"
      FilePath = "Animations\NPCThanatos\AttackHold\ThanatosAttackHold"
      Type = "Book"
      VideoTexture = "ThanatosAttackHold_Bink"
      EndFrame = 80
      NumAngles = 8
      NumFrames = 80
      PlaySpeed = 30.0
      StartFrame = 1
      OffsetY = -100.0
      Slides = {
        { DurationFrames = 1 Sound = "/Leftovers/SFX/RobeFlutter" Frame = 5 },
        { DurationFrames = 1 Sound = "/SFX/Player Sounds/ZagreusSwordLunge" Frame = 11 },
        { DurationFrames = 1 Sound = "/Leftovers/SFX/PlayerJumpMedium" Frame = 15 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 12 },
        { DurationFrames = 1 Sound = "/Leftovers/SFX/RobeFlutter" Frame = 21 },
        { DurationFrames = 1 Sound = "/Leftovers/World Sounds/TrainingMontageWhoosh" Frame = 74 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 51 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 59 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 67 },
      ]
      Material =
      {
        Ambient = 0.0
        Diffuse = 0.0
        Directionality = 0.0
      },
    },

    {
      Name = "ThanatosAssist"
      FilePath = "Animations\NPCThanatos\AttackHold\ThanatosAttackHold"
      Type = "Book"
      ChainTo="ThanatosTeleportAssist"
      VideoTexture = "ThanatosAttackHold_Bink"
	  SortMode = "Isometric"
      GroupName = "Standing"
      EndFrame = 80
      NumAngles = 8
      NumFrames = 80
      PlaySpeed = 30.0
      StartFrame = 1
      OffsetY = -100.0
      TimeModifierFraction = 0.1
      Slides = {
        { DurationFrames = 1 Sound = "/Leftovers/SFX/RobeFlutter" Frame = 5 },
        { DurationFrames = 1 Sound = "/SFX/Player Sounds/ZagreusSwordLunge" Frame = 11 },
        { DurationFrames = 1 Sound = "/Leftovers/SFX/PlayerJumpMedium" Frame = 15 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 12 },
        { DurationFrames = 1 Sound = "/Leftovers/SFX/RobeFlutter" Frame = 21 },
        { DurationFrames = 1 Sound = "/Leftovers/World Sounds/TrainingMontageWhoosh" Frame = 74 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 51 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 59 },
        { DurationFrames = 1 Sound = "/SFX/AresBladeSlice" Frame = 67 },
      ]
      Material =
      {
        Ambient = 0.0
        Diffuse = 0.0
        Directionality = 0.0
      },
    },


    {
      Name = "ThanatosTalkDismissal"
      FilePath = "Animations\NPCThanatos\EmoteDismissal\ThanatosEmoteDismissal"
      Type = "Book"
      VideoTexture = "ThanatosEmoteDismissal_Bink"
      EndFrame = 120
      NumAngles = 16
      NumFrames = 120
      PlaySpeed = 30.0
      StartFrame = 1
      OffsetY = -100.0
      CancelOnOwnerMove = true
      Material =
      {
        Ambient = 0.0
        Diffuse = 0.0
        Directionality = 0.0
      },
    },

    {
      Name = "ThanatosTalkDismissal_Start"
      InheritFrom = "ThanatosTalkDismissal"
      ChainTo = "ThanatosTalkDismissal_Loop"
      EndFrame = 34
      NumFrames = 120
      StartFrame = 1
      DisableOwnerRotation = true
      TimeModifierFraction = 0.0
    },

    {
      Name = "ThanatosTalkDismissal_Loop"
      InheritFrom = "ThanatosTalkDismissal"
      EndFrame = 94
      Loop = true
      NumFrames = 120
      StartFrame = 35
      DisableOwnerRotation = true
      TimeModifierFraction = 0.0
    },

    {
      Name = "ThanatosTalkDismissal_Return"
      InheritFrom = "ThanatosTalkDismissal"
      ChainTo = "ThanatosIdle"
      EndFrame = 120
      NumFrames = 120
      StartFrame = 95
      DisableOwnerRotation = true
      TimeModifierFraction = 0.0
    }, ]]
    {
      Name = "StoryExpansionFuryIdleInHouse",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "Enemy_Fury_IdleInHouse_Bink",
      EndFrame = 60,
      Loop = true,
      NumAngles = 32,
      NumFrames = 60,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -50.0,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },
    {
      Name = "StoryExpansionOrpheusIdle",
      ChainTo = "StoryExpansionOrpheusPlaying_Start",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "NPC_OrpheusIdle_Bink",
      EndFrame = 54,
      Loop = false,
      NumAngles = 8,
      NumFrames = 54,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -55,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },
    {
      Name = "StoryExpansionOrpheusPlaying",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "NPC_OrpheusIdlePlaying_Bink",
      EndFrame = 295,
      Loop = false,
      NumAngles = 8,
      NumFrames = 295,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -55,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },
    {
      Name = "StoryExpansionOrpheusPlaying_Start",
      InheritFrom = "StoryExpansionOrpheusPlaying",
      ChainTo = "StoryExpansionOrpheusPlaying_PlayingLoop",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "NPC_OrpheusIdlePlaying_Bink",
      EndFrame = 12,
      Loop = false,
      NumAngles = 8,
      NumFrames = 295,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -55,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },
    {
      Name = "StoryExpansionOrpheusPlaying_PlayingLoop",
      InheritFrom = "StoryExpansionOrpheusPlaying",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "NPC_OrpheusIdlePlaying_Bink",
      EndFrame = 285,
      Loop = true,
      NumAngles = 8,
      NumFrames = 295,
      PlaySpeed = 30.0,
      StartFrame = 13,
      OffsetY = -55,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },
    {
      Name = "StoryExpansionOrpheusPlaying_PlayingLoop_End",
      InheritFrom = "StoryExpansionOrpheusPlaying",
      ChainTo = "StoryExpansionOrpheusIdle",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "NPC_OrpheusIdlePlaying_Bink",
      EndFrame = 295,
      Loop = false,
      NumAngles = 8,
      NumFrames = 295,
      PlaySpeed = 30.0,
      StartFrame = 285,
      OffsetY = -55,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },
    {
      Name = "StoryExpansionNPCDusaIdle",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "NPC_DusaIdle_Bink",
      EndFrame = 80,
      Loop = true,
      NumAngles = 32,
      NumFrames = 80,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -25.0,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },
    {
      Name = "StoryExpansionPatroclusIdleStanding",
      FilePath = "Animations\\NPCThanatos\\Idle\\ThanatosIdle",
      Type = "Book",
      VideoTexture = "NPC_PatroclusIdleStanding_Bink",
      EndFrame = 60,
      AngleFromOwner = "Ignore",
      Loop = true,
      NumAngles = 16,
      NumFrames = 60,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -65.0,
      Scale = 1.25,
      CancelOnOwnerMove = true,
      Material =
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0,
      },
    },
    {
      Name = "StoryExpansionEurydiceIdle",
      ChainTo = "StoryExpansionEurydiceIdleSinging_Start",
      FilePath = "Animations\\NPCEurydice\\Idle\\EurydiceIdle",
      Type = "Book",
      VideoTexture = "NPC_EurydiceIdle_Bink",
      EndFrame = 54,
      Loop = true,
      NumAngles = 8,
      NumFrames = 54,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -50.0,
      Scale = 0.95,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
    },
    {
      Name = "StoryExpansionEurydiceIdleSinging",
      FilePath = "Animations\\NPCEurydice\\IdleSinging\\EurydiceIdleSinging",
      Type = "Book",
      VideoTexture = "NPC_EurydiceIdleSinging_Bink",
      EndFrame = 250,
      NumAngles = 8,
      NumFrames = 250,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -50.0,
      Scale = 0.95,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
    },
    {
      Name = "StoryExpansionEurydiceIdleSinging_Start",
      InheritFrom = "StoryExpansionEurydiceIdleSinging",
      ChainTo = "StoryExpansionEurydiceIdleSinging_SingingLoop",
      EndFrame = 12,
      NumFrames = 250,
      StartFrame = 1,
      TimeModifierFraction = 0.0,
      Type = "Book",
      VideoTexture = "NPC_EurydiceIdleSinging_Bink",
      NumAngles = 8,
      PlaySpeed = 30.0,
      OffsetY = -50.0,
      Scale = 0.95,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
    },
    {
      Name = "StoryExpansionEurydiceIdleSinging_SingingLoop",
      InheritFrom = "StoryExpansionEurydiceIdleSinging",
      EndFrame = 241,
      Loop = true,
      NumFrames = 250,
      StartFrame = 13,
      TimeModifierFraction = 0.0,
      Type = "Book",
      VideoTexture = "NPC_EurydiceIdleSinging_Bink",
      NumAngles = 8,
      PlaySpeed = 30.0,
      OffsetY = -50.0,
      Scale = 0.95,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
    },
    
    {
      Name = "StoryExpansionEurydiceIdleSinging_SingingLoop_End",
      InheritFrom = "StoryExpansionEurydiceIdleSinging",
      ChainTo = "StoryExpansionEurydiceIdle",
      EndFrame = 250,
      NumFrames = 250,
      StartFrame = 242,
      TimeModifierFraction = 0.0,
      Type = "Book",
      VideoTexture = "NPC_EurydiceIdleSinging_Bink",
      NumAngles = 8,
      PlaySpeed = 30.0,
      OffsetY = -50.0,
      Scale = 0.95,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
    },
    {
      Name = "StoryExpansionHypnosIdleSleeping",
      FilePath = "",
      Type = "Book",
      VideoTexture = "HypnosIdleSleeping_Bink",
      EndFrame = 74,
      Loop = true,
      NumAngles = 8,
      NumFrames = 74,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -50.0,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
    },
    {
      Name = "StoryExpansionHypnosSleepWakingSurprise",
      ChainTo = "HypnosIdleSitting",
      FilePath = "",
      Type = "Book",
      VideoTexture = "HypnosSleepWakingSurprise_Bink",
      EndFrame = 104,
      NumAngles = 8,
      NumFrames = 104,
      PlaySpeed = 30.0,
      StartFrame = 2,
      OffsetY = -50.0,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
    },
    {
      Name = "StoryExpansionHypnosIdleSitting",
      ChainTo = "HypnosSittingToSleep",
      FilePath = "",
      Type = "Book",
      VideoTexture = "HypnosIdleSitting_Bink",
      EndFrame = 74,
      Loop = true,
      NumAngles = 8,
      NumFrames = 74,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -50.0,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
    },
    {
      Name = "StoryExpansionHypnosIdleGreeting",
      ChainTo = "StoryExpansionHypnosIdleSitting",
      FilePath = "",
      Type = "Book",
      VideoTexture = "HypnosIdleGreeting_Bink",
      EndFrame = 74,
      NumAngles = 8,
      NumFrames = 74,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -50.0,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
    },
    {
      Name = "StoryExpansionHypnosSittingToSleep",
      ChainTo = "StoryExpansionHypnosIdleSleeping",
      FilePath = "",
      Type = "Book",
      VideoTexture = "HypnosSittingToSleep_Bink",
      EndFrame = 109,
      NumAngles = 8,
      NumFrames = 109,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -50.0,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
    },
    {
      Name = "StoryExpansionHypnosSleepingLoop",
      InheritFrom = "StoryExpansionHypnosIdleSleeping",
      Sound = "/VO/Hypnos_0002",
      StopSoundOnFinishFade = 0.2,
      DisableOwnerRotation = true,
      SoundAllowedAfterFrame = -1,
      TimeModifierFraction = 0.0,
    },
    {
      Name = "StoryExpansionHypnosWakeUp",
      InheritFrom = "StoryExpansionHypnosSleepWakingSurprise",
      DisableOwnerRotation = true,
      TimeModifierFraction = 0.0,
      Slides = {
        { DurationFrames = 1, Sound = "/SFX/HadesPaperFinish", Frame = 25 },
        { DurationFrames = 1, Sound = "/SFX/HadesPaperFinish", Frame = 30 },
        { DurationFrames = 1, Sound = "/SFX/HadesPaperPlace", Frame = 41 },
        { DurationFrames = 1, Sound = "/SFX/HadesPaperFinish", Frame = 50 },
        { DurationFrames = 1, Sound = "/SFX/HadesPaperLift", Frame = 86 },
      },
    },
    {
      Name = "StoryExpansionHypnosAwakeLoop",
      InheritFrom = "StoryExpansionHypnosIdleSitting",
      DisableOwnerRotation = false,
      TimeModifierFraction = 0.0,
    },
    {
      Name = "StoryExpansionHypnosReturnToSleeping",
      InheritFrom = "StoryExpansionHypnosSittingToSleep",
      ChainTo = "StoryExpansionHypnosSleepingLoop",
      DisableOwnerRotation = true,
      TimeModifierFraction = 0.0,
    },
    {
      Name = "StoryExpansionSisyphusIdle",
      FilePath = "Animations\\NPCEurydice\\Idle\\EurydiceIdle",
      Type = "Book",
      VideoTexture = "NPC_SisyphusIdle_Bink",
      AngleFromOwner = "Ignore",
      EndFrame = 75,
      Loop = true,
      NumFrames = 75,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -60.0,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
    },
    {
      Name = "StoryExpansionSisyphusIdleGreeting",
      ChainTo = "StoryExpansionSisyphusIdle",
      FilePath = "Animations\\NPCEurydice\\Idle\\EurydiceIdle",
      Type = "Book",
      VideoTexture = "NPC_SisyphusIdleGreeting_Bink",
      AngleFromOwner = "Ignore",
      EndFrame = 75,
      Loop = true,
      NumFrames = 75,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -60.0,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
    },
    {
      Name = "StoryExpansionSisyphusElbowing",
      ChainTo = "StoryExpansionSisyphusIdle",
      FilePath = "Animations\\NPCEurydice\\Idle\\EurydiceIdle",
      Type = "Book",
      VideoTexture = "NPC_SisyphusElbowing_Bink",
      AngleFromOwner = "Ignore",
      EndFrame = 75,
      Loop = true,
      NumFrames = 75,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -60.0,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
    },
    {
      Name = "StoryExpansionSisyphusExplaining",
      ChainTo = "StoryExpansionSisyphusIdle",
      FilePath = "Animations\\NPCEurydice\\Idle\\EurydiceIdle",
      Type = "Book",
      VideoTexture = "NPC_SisyphusExplaining_Bink",
      AngleFromOwner = "Ignore",
      EndFrame = 75,
      Loop = true,
      NumFrames = 75,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -60.0,
      Ambient = 0.0,
      CancelOnOwnerMove = true,
	  OnlyWhenVisible = true,
    },
    {
      Name = "StoryExpansionMinotaur_Idle",
      ChainTo = "StoryExpansionMinotaur_Walk",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "MinotaurIdle_Bink",

      EndFrame = 58,
      Loop = true,
      NumAngles = 64,
      NumFrames = 58,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -115.0,
      CancelOnOwnerMove = true,
      StepSoundOnFinishFade = 0.2,
	  OnlyWhenVisible = true,
      Material =
      {
        Ambient = 0.5,
        Diffuse = 0.5,
        },
        Slides = {
        { DurationFrames = 1, Sound = "/SFX/Enemy Sounds/Theseus/TheseusFootstepsWheatHeavy3" ,Frame = 11 },
        { DurationFrames = 1, Sound = "/SFX/Enemy Sounds/Theseus/TheseusFootstepsWheatHeavy3", Frame = 26 },
      },
    },
    {
      Name = "StoryExpansionMinotaur_Walk",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "MinotaurWalk_Bink",
      EndFrame = 38,
      Loop = true,
      NumAngles = 64,
      NumFrames = 38,
      PlaySpeed = 55.0,
      StartFrame = 1,
      OffsetY = -115.0,
      CancelOnOwnerMove = false,
      },
    {
      Name = "StoryExpansionMinotaurAttackSwings_PreAttack",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Slide",
      VideoTexture = "MinotaurAttackSwings_Bink",
      EndFrame = 70,
      HoldLastFrame = true,
      NumAngles = 32,
      NumFrames = 70,
      StartFrame = 1,
      OffsetY = -115.0,
      AllowRestart = true,
      Sound = "/SFX/Enemy Sounds/Minotaur/EmotePoweringUp",
      StopSoundOnFinishFade = 0.65,
      Slides = {

        { DurationFrames = 1 },

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },

        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 50, DangerDistance = 350 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
    },
    },
    {
      Name = "StoryExpansionMinotaurAttackSwings_Attack1",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
        MoveAnimation = "Minotaur_Walk",
      Type = "Slide",
      VideoTexture = "MinotaurAttackSwings_Bink",
      EndFrame = 70,
      HoldLastFrame = true,
      NumAngles = 32,
      NumFrames = 70,
      StartFrame = 1,
      OffsetY = -115.0,
      VisualFxDistanceMax = 30.0,
      VisualFxDistanceMin = 30.0,
      ActiveVisualFxCap = 40,
      AllowRestart = true,
      DangerDistance = 350,
      Slides = {

        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 999 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
    },
    },
    {
      Name = "StoryExpansionMinotaurAttackSwings_Attack2",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
          MoveAnimation = "Minotaur_Walk",
      Type = "Slide",
      VideoTexture = "MinotaurAttackSwings_Bink",
      EndFrame = 70,
      HoldLastFrame = true,
      NumAngles = 32,
      NumFrames = 70,
      StartFrame = 1,
      OffsetY = -115.0,
      VisualFxDistanceMax = 30.0,
      VisualFxDistanceMin = 30.0,
      ActiveVisualFxCap = 40,
      AllowRestart = true,
      DangerDistance = 350,
      Slides = {

        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
    },
    },
    {
      Name = "StoryExpansionMinotaurAttackSwings_ReturnToIdle",
            ChainTo = "StoryExpansionMinotaur_Idle",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Slide",
      VideoTexture = "MinotaurAttackSwings_Bink",
      EndFrame = 70,
      HoldLastFrame = false,
      NumAngles = 32,
      NumFrames = 70,
      StartFrame = 1,
      OffsetY = -115.0,
      VisualFxDistanceMax = 30.0,
      VisualFxDistanceMin = 30.0,
      ActiveVisualFxCap = 40,
      AllowRestart = true,
      DangerDistance = 350,
      Slides = {

        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 30 },

        { DurationFrames = 2 },

        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
    },
    },
    {
      Name = "StoryExpansionMinotaurAttackSwings_PreAttackLeap",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Slide",
      VideoTexture = "MinotaurAttackLeap_Bink",
      EndFrame = 124,
      NumAngles = 32,
      NumFrames = 124,
      StartFrame = 1,
      OffsetY = -115.0,
      AllowRestart = true,
      DangerDistance = 350,
      Slides = {

        { DurationFrames = 1 },

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        

        { DurationFrames = 1 },
        { DurationFrames = 1, Sound = "/SFX/Enemy Sounds/WrechPunchSwing" },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        

        { DurationFrames = 1 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        

        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
    },
    },
    {
      Name = "StoryExpansionMinotaurAttackSwings_AirLoop",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Slide",
      VideoTexture = "MinotaurAttackLeap_Bink",
      EndFrame = 124,
      NumAngles = 32,
      NumFrames = 124,
      StartFrame = 1,
      OffsetY = -115.0,
      Loop = true,
      DangerDistance = 350,
      Slides = {

        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        

        { DurationFrames = 0 },
        { DurationFrames = 4 },
        
        { DurationFrames = 4 },
        { DurationFrames = 4},
        { DurationFrames = 4 },
        { DurationFrames = 4 },
        { DurationFrames = 4 },
        { DurationFrames = 4 },
        { DurationFrames = 4 },
        { DurationFrames = 4 },
        

        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
    },
    },
    {
      Name = "StoryExpansionMinotaurAttackSwings_AttackLeap",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Slide",
      HoldLastFrame = true,
      VideoTexture = "MinotaurAttackLeap_Bink",
      EndFrame = 44,
      NumAngles = 32,
      NumFrames = 124,
      StartFrame = 31,
      OffsetY = -115.0,
      DangerDistance = 350,
      Slides = {

       
        { DurationFrames = 1, VisualFx = "StoryExpansionMinotaurSwordSwipeOverhead" },
        
        { DurationFrames = 1, Sound = "/SFX/Enemy Sounds/Minotaur/MinotaurFootstepsHugeRUSH" },
        { DurationFrames = 1, Sound = "/SFX/Enemy Sounds/Minotaur/MinotaurFootstepsHugeRUSH" },
        { DurationFrames = 1, Sound = "/SFX/StabSplatterEndSequence", VisualFx = "FrogFamiliarLandDust" },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
         

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },

    },
    },
    {
      Name = "StoryExpansionMinotaurAttackSwings_AttackLeapReturnToIdle",
      ChainTo = "StoryExpansionMinotaur_Walk",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Slide",
      VideoTexture = "MinotaurAttackLeap_Bink",
      EndFrame = 124,
      NumAngles = 32,
      NumFrames = 124,
      StartFrame = 1,
      OffsetY = -115.0,
      CancelOnOwnerMove = true,
      DangerDistance = 350,
      Slides = {

        { DurationFrames = 0 },
     
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
       

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
       

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
       

        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0},
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
         

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },
         
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
     
      
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },


        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
       

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
         

        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        

        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },

        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },

        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },

    },
    },
    {
      Name = "StoryExpansionTheseus_Walk",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "TheseusWalk_Bink",
      EndFrame = 30,
      Loop = true,
      NumAngles = 64,
      NumFrames = 30,
      PlaySpeed = 36.0,
      StartFrame = 1,
      OffsetY = -90.0,
      NativeMoveSpeed = 260.0,
      Material = 
      {
        Ambient = 0.0,
        Diffuse = 0.0,
      },
      Slides = {
        { DurationFrames = 1, Sound = "/SFX/Enemy Sounds/Theseus/TheseusFootstepsWheatHeavy3" ,Frame = 11 },
        { DurationFrames = 1, Sound = "/SFX/Enemy Sounds/Theseus/TheseusFootstepsWheatHeavy3", Frame = 26 },
      },
    },
    {
      Name = "StoryExpansionTheseus_Idle",
      FilePath = "Animations\\NPCThanatos\\IdleInhouse\\ThanatosIdleInhouse",
      Type = "Book",
      VideoTexture = "TheseusIdle_Bink",
      EndFrame = 40,
      Loop = true,
      NumAngles = 64,
      NumFrames = 40,
      PlaySpeed = 30.0,
      StartFrame = 1,
      OffsetY = -90.0,
      CancelOnOwnerMove = true,
      Material = 
      {
        Ambient = 0.0,
        Diffuse = 0.0,
        Directionality = 0.0
      },
    },
    {
      Name = "StoryExpansionTheseusSpearSpin_PreAttack",
      FilePath = "",
      Type = "Slide",
      VideoTexture = "TheseusSpearSpin_Bink",
      EndFrame = 114,
      NumAngles = 32,
      NumFrames = 114,
      StartFrame = 1,
      OffsetY = -90.0,
      AllowRestart = true,
      OwnerNoInvulnerableCoverage = true,
      Slides = {

        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 1, DangerDistance = 350 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
      },
      Material = 
      {
        Ambient = 0.0,
        Diffuse = 0.0,
      },
    },

    
    {
      Name = "StoryExpansionTheseusSpearSpin_Attack",
      FilePath = "",
      Type = "Slide",
      VideoTexture = "TheseusSpearSpin_Bink",
      EndFrame = 114,
      NumAngles = 32,
      NumFrames = 114,
      StartFrame = 1,
      OffsetY = -90.0,
      OwnerNoInvulnerableCoverage = true,
      DangerDistance = 350,
      Slides = {

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
      },
      Material = 
      {
        Ambient = 0.0,
        Diffuse = 0.0
      },
    },

    
    {
      Name = "StoryExpansionTheseusSpearSpin_ReturnToIdle",
      ChainTo = "StoryExpansionTheseus_Idle",
      FilePath = "",
      Type = "Slide",
      VideoTexture = "TheseusSpearSpin_Bink",
      EndFrame = 114,
      NumAngles = 32,
      NumFrames = 114,
      StartFrame = 1,
      OffsetY = -90.0,
      AllowRestart = true,
      Slides = {

        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        { DurationFrames = 0 },
        
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },

        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },

        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
        { DurationFrames = 2 },
      },
      Material = 
      {
        Ambient = 0.0,
        Diffuse = 0.0,
      },
    },
}

local animationFile = rom.path.combine(rom.paths.Content(), 'Game\\Animations\\NPC_General_VFX.sjson')


for k, newData in pairs(newAnimations) do
    sjson.hook(animationFile, function(data)
        table.insert(data.Animations, newData)
    end)
end