-- Strong but drawback
-- Should be powerful, but very late game, but also very fun
-- Could theme around the monstrosity arcana card - purge for a random arcana card, less than
-- you can purge with Chronos